development:
  server: "http://176.58.103.250:9292/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
test:
  server: "http://176.58.103.250:9292/faye"
  secret_token: "secret"
production:
  server: "http://176.58.103.250:9292/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
